version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=derrick
      - DOCKER_INFLUXDB_INIT_PASSWORD=derrick123
      - DOCKER_INFLUXDB_INIT_ORG=derrick
      - DOCKER_INFLUXDB_INIT_BUCKET=shaker_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=derrick-token
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:9.6.4
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
  grafana-data: